#!/bin/bash
#用于python文件头生成
[ -z "$1" ] && exit 1

date_path=$HOME'/.vim/template/dynamic'
datetime=`bash $date_path'/datetime.sh'`
filename=`echo ${1}`
year=`date +%Y`

cat << EOF
#!/usr/bin/env python3
# -*- coding=utf-8 -*-

#################################################################################
# Copyright (C) $year All rights reserved. 
# 文件名称：$filename
# 创 建 者：樊聪
# 邮    箱：fancong20@163.com
# 创建日期：$datetime
# 描    述：
#  
# 更新日志：
#  
#################################################################################

'a ${filename%%.*} module'

__author__ = '樊聪'



if __name__ == '__main__':

EOF
